### ISSUE TITLE
wp-download error while running it (ImportError: No module named wp_download)

### ISSUE THREAD

**Issue by ajmanee** [babilen/wp-download#10]
I tried to run the command but it always giving me an error on this 
(
_wp-download -v /Users/ali/Documents/wiki_samples/
Traceback (most recent call last):
  File "/usr/local/bin/wp-download", line 30, in <module>
    import wp_download as wpd
ImportError: No module named wp_download_
)

any hint on this

**Comment by babilen** [comment]
How did you install it?

**Comment by jcarlostrillo** [comment]
I had the same issue. I ran the following step to install the tool "sudo python setup.py install --prefix=/usr/local".
I'm running under OS X with python 2.7.

**Comment by babilen** [comment]
I take it that you installed directly from the git checkout?

**Comment by jcarlostrillo** [comment]
Thanks for your reply! I merged two problems under the same issue (sorry). I'll try to be clear now:

I'm working under OS X 10.10.5, with Python 2.7.10. I clone the repository, after that I tried to run the following instruction:

> sudo python setup.py install --prefix=/usr/local

The installacion process was okay. But when I try to perform some operation, it fails and I've the same message that @ajmanee started this issue:

> Traceback (most recent call last):
  File "/usr/local/bin/wp-download", line 30, in <module>
    import wp_download as wpd
ImportError: No module named wp_download

I hope now the information about the issue it's clear. Thanks again!

**Comment by babilen** [comment]
Yeah, that helps tremendously. I typically install wp-download in a virtualenv as that manages my `PYTHONPATH`. Did you ensure that yours include the respective directories in `/usr/local` ? What does "python -c "import sys; print sys.path"` give you? Furthermore: If you manually install into `/usr/local` you might want to consider using stow (cf. https://www.gnu.org/software/stow/) to manage that installation as they would be otherwise tricky to remove.

For comparison this is what I get on Debian when I run the aforementioned command:
```
$ python -c "import sys; print sys.path"
['', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gst-0.10', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7']
```

**Comment by jcarlostrillo** [comment]
Hello again!

Thanks for your reply and your patient again! It was very helpfully and thanks to it i asked me a few questions. I tried to import the packaged not found manually but it doesn't work (the problem was the same). Also I removed an old version of Python that I had in my computer (now it's working with 2.7.10, as I mentioned in the last post). So at the end I tried to launch again the two process of installation: the first of one, execution the setup.py fails again (it gave to me the same error). So I tried with the second way and.... it's working. I used "pip" to install with the following instruction and it works:

> sudo pip install wp-download

Furthermore I needed to install a few dependencies more: 

> sudo pip install progressbar

Now it's working. Thanks a lot again!

**Comment by babilen** [comment]
Please note that you'll get the version on pypi if you install via pip, but the current git HEAD if you install  with `setup.py install ...`. Both are fine and the changes in git are mostly related to Python2/Python3 compatibility and a planned switch to Python 3.

If you still like to use the version installed from git HEAD, you'd have to make sure that your `PYTHONPATH` includes the respective directories in `/usr/local`. Having said that, my recommendation would be to create a virtualenv with virtualenvwrappet (cf. https://virtualenv.readthedocs.org/en/latest/ and https://virtualenvwrapper.readthedocs.org/en/latest/) and install `wp-download` in there with a simple `setup.py install`. It will manage your `PATH` and `PYTHONPATH` and allows you to remove it easily.

The released version installed with pip should work though.

**Comment by jcarlostrillo** [comment]
Ok! So I'll try to create a virtualenv, I think everything will've more easy there.
Thanks again!

**Comment by babilen** [comment]
You are welcome. Enjoy! Does this solve it for you too, @ajmanee ?
